param(
  [Parameter(Mandatory=$true)][string]$QairtSdkRoot,
  [Parameter(Mandatory=$true)][string]$ExpectedBuildId,
  [ValidateRange(1,20)][int]$Repetitions=3,
  [long[]]$Seeds=@(20260710,20260711,20260712,20260713,20260714),
  [string]$ReportRoot,
  [switch]$SkipBuild,
  [switch]$SkipRegression,
  [switch]$RunPerformance
)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
if(!$ReportRoot){$ReportRoot=Join-Path $root ('build\reports\qnn-htp-full-step-'+(Get-Date -Format yyyyMMdd-HHmmss))}
[IO.Directory]::CreateDirectory((Join-Path $ReportRoot 'runs'))|Out-Null
$env:ANDROID_HOME=Join-Path $env:LOCALAPPDATA 'Android\Sdk';$env:ANDROID_SDK_ROOT=$env:ANDROID_HOME
$adb=Join-Path $env:ANDROID_HOME 'platform-tools\adb.exe';$apk=Join-Path $root 'app\build\outputs\apk\debug\app-debug.apk'
$package='com.yuubinnkyoku.phonelm';$activity="$package/.MainActivity"
$online=@();foreach($line in (& $adb devices)){if($line-match '^(\S+)\s+device$'){$online+=$Matches[1]}}
if($online.Count-ne 1){throw "Expected exactly one online ADB device; found $($online.Count)"};$device=$online[0]
function Adb([string[]]$a){$o=& $adb -s $device @a 2>&1;if($LASTEXITCODE-ne 0){throw "ADB failed (endpoint redacted): $($a-join ' ')`n$o"};$o}
function Fields([string]$x){$h=[ordered]@{};foreach($l in ($x-split "`r?`n")){if($l-match '^([A-Za-z0-9_]+)=(.*)$'){$h[$Matches[1]]=$Matches[2]}};$h}
function DeviceState{$b=(Adb @('shell','dumpsys','battery'))-join "`n";$t=(Adb @('shell','dumpsys','thermalservice'))-join "`n";[pscustomobject]@{temperature=if($b-match '(?m)^\s*temperature:\s*(\d+)'){[double]$Matches[1]/10}else{$null};level=if($b-match '(?m)^\s*level:\s*(\d+)'){$Matches[1]}else{'unknown'};charging=if($b-match '(?m)^\s*status:\s*(\d+)'){$Matches[1]}else{'unknown'};thermal=if($t-match 'mStatus=(\d+)'){$Matches[1]}else{'unknown'};elapsed=[Environment]::TickCount64}}
function Guard([string]$phase){$v=DeviceState;Write-Host "$phase temperature=$($v.temperature)C thermal_status=$($v.thermal)";if($null-ne$v.temperature-and$v.temperature-ge45){throw "Thermal guard: $($v.temperature)C"};$v}
function RunMode([string]$mode,[string]$name,[int]$b,[int]$i,[int]$h,[int]$o,[int]$steps,[int]$samples,[int]$epochs,[double]$lr,[long]$seed,[bool]$benchmark){
  $path=Join-Path $ReportRoot "runs\$name.txt";$x=''
  if(Test-Path $path){$x=[IO.File]::ReadAllText($path);if($x-notmatch '(?m)^status=SUCCESS$'){$x=''}}
  $before=Guard $name
  if(!$x){
    Adb @('shell','am','force-stop',$package)|Out-Null;Adb @('shell','run-as',$package,'rm','-f','files/device-test-result.txt')|Out-Null
    $rate=$lr.ToString('R',[Globalization.CultureInfo]::InvariantCulture);$bm=if($benchmark){'true'}else{'false'}
    Adb @('shell','am','start','-W','-n',$activity,'--es','phonelm.mode',$mode,'--ei','phonelm.batch_size',"$b",'--ei','phonelm.dimension',"$i",'--ei','phonelm.hidden_dimension',"$h",'--ei','phonelm.output_dimension',"$o",'--ei','phonelm.steps',"$steps",'--ei','phonelm.sample_count',"$samples",'--ei','phonelm.epochs',"$epochs",'--ei','phonelm.correctness_interval','1','--ez','phonelm.benchmark_mode',$bm,'--es','phonelm.learning_rate',$rate,'--es','phonelm.seed',"$seed")|Out-Null
    for($n=0;$n-lt2400;$n++){Start-Sleep -Milliseconds 500;$x=(& $adb -s $device shell run-as $package cat files/device-test-result.txt 2>$null)-join "`n";if($x-match '(?m)^status=(SUCCESS|FAILED)$'){break}}
    [IO.File]::WriteAllText($path,$x,[Text.UTF8Encoding]::new($false))
  }
  $after=DeviceState;$f=Fields $x
  if($f.status-ne'SUCCESS'){throw "$name status=$($f.status) error=$($f.error)"};if($f.cpu_fallback-ne'false'){throw "$name CPU fallback"};if($f.nan_inf-ne'false'){throw "$name NaN/Inf"}
  [pscustomobject]@{fields=$f;before=$before;after=$after}
}
Push-Location $root
try{
  Write-Host 'Estimated duration: correctness and 5 seeds 10-20 minutes; performance and regressions add 20-40 minutes.'
  if(!$SkipBuild){.\gradlew.bat :app:clean :app:assembleDebug '-Pphonelm.enableQnn=true' "-Pqairt.sdkRoot=$QairtSdkRoot" "-Pqairt.expectedBuildId=$ExpectedBuildId" --no-daemon;if($LASTEXITCODE-ne0){throw'build failed'};& "$PSScriptRoot\audit_qnn_apk.ps1" -ApkPath $apk -QairtSdkRoot $QairtSdkRoot -ExpectedBuildId $ExpectedBuildId -ReportPath (Join-Path $ReportRoot 'apk-audit.txt')}
  Adb @('install','-r',$apk)|Out-Null
  $mse=RunMode QNN_HTP_MSE_CHECK mse-dp-micro 2 4 5 3 1 2 0 .1 $Seeds[0] $false
  $sgd=RunMode QNN_HTP_SGD_CHECK sgd-micro 2 4 5 3 1 2 0 .1 $Seeds[0] $false
  @([pscustomobject]@{test='mse_dp';op_method=$mse.fields.mse_op_method;input_shape=$mse.fields.input_shape;output_shape=$mse.fields.loss_output_shape;max_abs_error=$mse.fields.mse_abs_error;mean_abs_error='';max_relative_error='';cpu_fallback=$mse.fields.cpu_fallback;status=$mse.fields.status},[pscustomobject]@{test='dp';op_method=$mse.fields.dp_op_method;input_shape=$mse.fields.input_shape;output_shape=$mse.fields.input_shape;max_abs_error=$mse.fields.dp_max_abs_error;mean_abs_error=$mse.fields.dp_mean_abs_error;max_relative_error=$mse.fields.dp_max_relative_error;cpu_fallback=$mse.fields.cpu_fallback;status=$mse.fields.status},[pscustomobject]@{test='sgd';op_method=$sgd.fields.sgd_op_method;input_shape='2x3';output_shape='2x3';max_abs_error=$sgd.fields.sgd_max_abs_error;mean_abs_error=$sgd.fields.sgd_mean_abs_error;max_relative_error=$sgd.fields.sgd_max_relative_error;cpu_fallback=$sgd.fields.cpu_fallback;status=$sgd.fields.status})|Export-Csv -NoTypeInformation -Encoding utf8 (Join-Path $ReportRoot 'op-correctness.csv')
  $small=RunMode QNN_HTP_MLP_FULL_STEP full-step-small 2 4 5 3 10 20 0 .1 $Seeds[0] $false
  [pscustomobject]$small.fields|Export-Csv -NoTypeInformation -Encoding utf8 (Join-Path $ReportRoot 'full-step-correctness.csv')
  $seedRows=@();$trajectoryRows=@()
  foreach($seed in $Seeds){foreach($mode in @('QNN_CPU_MLP_TRAINING','QNN_HTP_MLP_FUSED_BACKWARD','QNN_HTP_MLP_FULL_STEP')){$r=RunMode $mode "seed-$seed-$mode" 8 128 128 64 640 512 10 .5 $seed $false;$f=$r.fields;$seedRows+=[pscustomobject]@{seed=$seed;mode=$mode;sample_count=512;batch_size=8;input_dim=128;hidden_dim=128;output_dim=64;epochs=10;learning_rate=.5;initial_loss=$f.initial_loss;final_loss=$f.final_loss;loss_reduction_ratio=$f.loss_reduction_ratio;prediction_mse=$f.prediction_mse;prediction_max_abs_error=$f.prediction_max_abs_error;cpu_htp_final_loss_difference=$f.cpu_htp_final_loss_difference;cpu_htp_prediction_max_abs_difference=$f.cpu_htp_prediction_max_abs_difference;cpu_htp_w1_max_abs_difference=$f.cpu_htp_w1_max_abs_difference;cpu_htp_w2_max_abs_difference=$f.cpu_htp_w2_max_abs_difference;forward_backend=$f.forward_backend;loss_backend=if($f.loss_backend){$f.loss_backend}else{'CPU'};dp_backend=if($f.dp_backend){$f.dp_backend}else{'CPU'};backward_backend=if($f.backward_backend){$f.backward_backend}else{$f.dw1_backend};optimizer_backend=$f.optimizer_backend;weight_handoff_method=$f.weight_handoff_method;execute_count_per_step=$f.execute_count_per_step;cpu_fallback=$f.cpu_fallback;nan_inf=$f.nan_inf;status=$f.status};if($mode-eq'QNN_HTP_MLP_FULL_STEP'){foreach($k in $f.Keys){if($k-match '^trajectory_(\d+)_(.+)$'){$trajectoryRows+=[pscustomobject]@{seed=$seed;step=[int]$Matches[1];metric=$Matches[2];value=$f[$k]}}}}}}
    $seedRows|Export-Csv -NoTypeInformation -Encoding utf8 (Join-Path $ReportRoot 'seeds.csv')
  $trajectoryWide=@();foreach($g in ($trajectoryRows|Group-Object seed,step)){$first=$g.Group[0];$row=[ordered]@{seed=$first.seed;step=$first.step};foreach($m in $g.Group){$row[$m.metric]=$m.value};$trajectoryWide+=[pscustomobject]$row};$trajectoryWide|Sort-Object seed,step|Export-Csv -NoTypeInformation -Encoding utf8 (Join-Path $ReportRoot 'weight-trajectory.csv')
  $perf=@();if($RunPerformance){$shapes=@(@(2,4,5,3),@(8,128,128,64),@(8,256,256,128),@(32,256,256,128));for($n=1;$n-le$Repetitions;$n++){foreach($sh in $shapes){$htpOrder=if($n%2){@('QNN_HTP_MLP_FUSED_BACKWARD_BENCHMARK','QNN_HTP_MLP_FULL_STEP_BENCHMARK')}else{@('QNN_HTP_MLP_FULL_STEP_BENCHMARK','QNN_HTP_MLP_FUSED_BACKWARD_BENCHMARK')};$order=if($n%2){@('QNN_CPU_MLP_TRAINING')+$htpOrder}else{$htpOrder+@('QNN_CPU_MLP_TRAINING')};foreach($mode in $order){$r=RunMode $mode "perf-b$($sh[0])-i$($sh[1])-h$($sh[2])-o$($sh[3])-r$n-$mode" $sh[0] $sh[1] $sh[2] $sh[3] 100 512 0 .5 $Seeds[0] $true;$f=$r.fields;$perf+=[pscustomobject]@{mode=$mode;batch_size=$sh[0];input_dim=$sh[1];hidden_dim=$sh[2];output_dim=$sh[3];run_index=$n;graph_count=if($mode-like'*FULL_STEP*'){1}elseif($mode-like'*FUSED*'){2}else{0};execute_count_per_step=if($f.execute_count_per_step){$f.execute_count_per_step}elseif($mode-like'*FUSED*'){2}else{0};initialization_us=if($f.runtime_initialization_us){$f.runtime_initialization_us}else{0};graph_create_us=$f.training_graph_create_us;graph_finalize_us=$f.training_graph_finalize_us;first_execute_us=$f.first_execute_us;steady_execute_median_us=$f.steady_execute_median_us;weight_handoff_median_us=$f.weight_buffer_handoff_median_us;full_step_median_us=$f.full_step_median_us;total_time_us=([double]$f.runtime_initialization_us+100*[double]$f.full_step_median_us);temperature_before=$r.before.temperature;temperature_after=$r.after.temperature;thermal_status_before=$r.before.thermal;thermal_status_after=$r.after.thermal;cpu_fallback=$f.cpu_fallback;status=$f.status}}}};$perf|Export-Csv -NoTypeInformation -Encoding utf8 (Join-Path $ReportRoot 'performance.csv')}
  $initialization=$perf|Select-Object mode,batch_size,input_dim,hidden_dim,output_dim,run_index,graph_count,initialization_us,graph_create_us,graph_finalize_us,first_execute_us;$initialization|Export-Csv -NoTypeInformation -Encoding utf8 (Join-Path $ReportRoot 'initialization.csv')
  $breakEven=@();foreach($g in ($perf|Group-Object batch_size,input_dim,hidden_dim,output_dim)){$old=[double](($g.Group|Where-Object mode -eq QNN_HTP_MLP_FUSED_BACKWARD_BENCHMARK|Measure-Object full_step_median_us -Average).Average);$new=[double](($g.Group|Where-Object mode -eq QNN_HTP_MLP_FULL_STEP_BENCHMARK|Measure-Object full_step_median_us -Average).Average);$oldInit=[double](($g.Group|Where-Object mode -eq QNN_HTP_MLP_FUSED_BACKWARD_BENCHMARK|Measure-Object initialization_us -Average).Average);$newInit=[double](($g.Group|Where-Object mode -eq QNN_HTP_MLP_FULL_STEP_BENCHMARK|Measure-Object initialization_us -Average).Average);$saving=$old-$new;$delta=$newInit-$oldInit;$breakEven+=[pscustomobject]@{shape=$g.Name;old_execute_count_per_step=2;new_execute_count_per_step=1;old_full_step_us=$old;new_full_step_us=$new;speedup=if($new-gt0){$old/$new}else{''};initialization_delta_us=$delta;per_step_saving_us=$saving;break_even_steps=if($saving-gt0){[math]::Max(1,[math]::Ceiling([math]::Max(0,$delta)/$saving))}else{'none'}}};$breakEven|Export-Csv -NoTypeInformation -Encoding utf8 (Join-Path $ReportRoot 'break-even.csv')
  if(!$SkipRegression){& "$PSScriptRoot\run_qnn_device_tests.ps1" -QairtSdkRoot $QairtSdkRoot -ExpectedBuildId $ExpectedBuildId;& "$PSScriptRoot\run_qnn_training_tests.ps1" -QairtSdkRoot $QairtSdkRoot -ExpectedBuildId $ExpectedBuildId -BatchSize 8 -InputDim 128 -Steps 100 -LearningRate 5 -SkipBuild -SkipRegression;& "$PSScriptRoot\run_qnn_htp_backward_tests.ps1" -QairtSdkRoot $QairtSdkRoot -ExpectedBuildId $ExpectedBuildId -Repetitions 1 -Seeds 20260710 -SkipBuild -SkipRegression;& "$PSScriptRoot\run_qnn_htp_mlp_tests.ps1" -QairtSdkRoot $QairtSdkRoot -ExpectedBuildId $ExpectedBuildId -Repetitions 1 -Seeds 20260710 -SkipBuild -SkipRegression;& "$PSScriptRoot\run_qnn_htp_fused_backward_tests.ps1" -QairtSdkRoot $QairtSdkRoot -ExpectedBuildId $ExpectedBuildId -Repetitions 1 -Seeds 20260710 -SkipBuild -SkipRegression}
  $summary=[ordered]@{qairt_build_id=$ExpectedBuildId;full_step_graph='phonelm_mlp_training_step';nodes=16;loss_op='Subtract+Multiply+ReduceMean';reduction_axes=@(0,1);weight_handoff='ping-pong binding';in_place_alias=$false;old_execute_count_per_step=2;new_execute_count_per_step=1;cpu_responsibilities=@('mini-batch supply','graph control','weight buffer handoff','result access','correctness checks');cpu_fallback=$false;status='SUCCESS'}
  [IO.File]::WriteAllText((Join-Path $ReportRoot 'summary.json'),($summary|ConvertTo-Json -Depth 5),[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $ReportRoot 'summary.md'),"# QNN HTP full training step`n`nstatus: SUCCESS`n`nQAIRT Build ID: $ExpectedBuildId`n`nHTP graph: forward, MSE loss, dP, dW2, dH, ReLU backward, dW1, SGD. CPU: mini-batch supply, graph control, weight ping-pong handoff, result access, correctness and reporting.`n`nExecute count: 2 -> 1 per step.`n",[Text.UTF8Encoding]::new($false));Write-Host "report_root=$ReportRoot`nstatus=SUCCESS"
}finally{Pop-Location}